# Generated by Django 4.2.13 on 2024-06-09 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIoT",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("located_at", models.CharField(max_length=250)),
                ("longitude", models.CharField(blank=True, max_length=250, null=True)),
                ("latitude", models.CharField(blank=True, max_length=250, null=True)),
                ("water_name", models.CharField(blank=True, max_length=250, null=True)),
                ("zone_id", models.SlugField(blank=True, max_length=255, null=True)),
                ("api_key", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "ordering": ["located_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPerson",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="waterParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ph", models.CharField(blank=True, max_length=250, null=True)),
                ("oxygen", models.CharField(blank=True, max_length=250, null=True)),
                ("turbidity", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "temperature",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("harvesting_time", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-harvesting_time"],
            },
        ),
        migrations.CreateModel(
            name="WaterQualityPred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("harvesting_time", models.DateTimeField(auto_now=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.waterparameters",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WaterParameterPred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lower_border", models.DateTimeField(auto_now=True)),
                (
                    "data_source",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("upper_border", models.DateTimeField(auto_now=True)),
                ("parameter", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.userperson",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
