# Generated by Django 4.2.13 on 2024-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_alter_useriot_water_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waterqualitypred",
            name="harvesting_time",
        ),
        migrations.AddField(
            model_name="waterqualitypred",
            name="quality",
            field=models.BooleanField(default=False),
        ),
    ]
