# Generated by Django 4.2.13 on 2024-06-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_remove_waterqualitypred_harvesting_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterparameters",
            name="site",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
