# Generated by Django 4.2.13 on 2024-06-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_waterparameters_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterparameterpred",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainApp.userperson"
            ),
        ),
    ]
