# Generated by Django 4.2.13 on 2024-06-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0005_alter_waterparameterpred_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterparameterpred",
            name="lower_border",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="waterparameterpred",
            name="upper_border",
            field=models.DateTimeField(),
        ),
    ]
